'''Configurações de fontes para a aplicação'''

'''Fontes principais'''
FONT_FAMILY_PRIMARY= 'Segoe UI'
FONT_FAMILY_MONO = 'Courier New'

'''Tamanho de Fonte'''
FONT_SIZE_SMALL = 10
FONT_SIZE_NORMAL = 12
FONT_SIZE_MEDIUM = 14
FONT_SIZE_LARGE = 16
FONT_SIZE_XLARGE = 18
FONT_SIZE_XXLARGE = 24

'''Tuplas de fonte (família, tamanho, estilo)'''
FONT_TITLE = (FONT_FAMILY_PRIMARY, FONT_SIZE_XXLARGE, 'bold')
FONT_SUBTITLE = (FONT_FAMILY_PRIMARY, FONT_SIZE_XLARGE, 'bold')
FONT_HEADING = (FONT_FAMILY_PRIMARY, FONT_SIZE_MEDIUM, 'bold')
FONT_LABEL = (FONT_FAMILY_PRIMARY, FONT_SIZE_NORMAL, 'normal')
FONT_LABEL_BOLD = (FONT_FAMILY_PRIMARY, FONT_SIZE_NORMAL, 'bold')
FONT_SMALL = (FONT_FAMILY_PRIMARY, FONT_SIZE_NORMAL, 'normal')
FONT_SMALL_BOLD = (FONT_FAMILY_PRIMARY, FONT_SIZE_NORMAL, 'bold')
FONT_BUTTON = (FONT_FAMILY_PRIMARY, FONT_SIZE_NORMAL, 'normal')
FONT_ENTRY = (FONT_FAMILY_PRIMARY, FONT_SIZE_NORMAL, 'normal')